config/routes.rb
Rails.application.routes.draw do

    get 'signup', to: 'users#new', as: 'signup'
    get 'login', to: 'sessions#new', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'


  resources :sessions

  resources :users

  root 'users#index'

  get 'garages/' => 'garages#index'

  get 'garages/new' => 'garages#new'

  get 'garages/:id' => 'garages#show', as: :garage

  post 'garages/'  => 'garages#create'

  get 'garages/:id/edit' => 'garages#edit', as: :edit_garage

  patch 'garages/:id' => 'garages#update'

  delete  'garages/:id' => 'garages#destroy'

end

app/models/garage.rb
class Garage
  include Mongoid::Document
  field :date, type: Date
  field :year, type: Integer
  field :make, type: String
  field :model, type: String
  field :price, type: Integer
  field :mileage, type: Integer
  field :phone, type: Integer
  field :email, type: String
  field :comments, type: String
end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword
   has_secure_password
  field :email, type: String
  field :password_digest, type: String




  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id] 
  end
  helper_method :current_user
end

app/controllers/garages_controller.rb
class GaragesController < ApplicationController

	def index
		@garages = Garage.all
	end

	def show
		@garage = Garage.find(params[:id])
	end

	def new
		@garage = Garage.new
	end

	
	def create
	@garage = Garage.new(params.require(:garage).permit(:date, :year, :make, :model, :price, :mileage, :phone, :email, :comments))
		if @garage.save
			redirect_to garages_path
		else 
			render 'new'
		end
	end

	def edit
		@garage = Garage.find(params[:id])
	end

	def update
		@garage = Garage.find(params[:id])
		if @garage.update_attributes(params.require(:garage).permit(:date, :year, :make, :model, :price, :mileage, :phone, :email, :comments))
			redirect_to garages_path
		else
			render 'edit'
		end
	end

	def destroy
		@garage = Garage.find(params[:id])
		@garage.destroy
		redirect_to garages_path
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        user = User.where(email: params[:email]).first
        # first make sure we actually find a user
        # then see if user authenticates
        if user && user.authenticate(params[:password])
            # sets the cookie to the browser
            session[:user_id] = user.id.to_s
            redirect_to root_url, notice: "Logged in!"
        else
            flash.now.alert = "Email or password is invalid"
            render "new"
            # redirect_to new_session_path
        end
    end

    def destroy
        # Kill our cookies!
        reset_session
        redirect_to root_path, notice: "Logged out!"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def index

    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
        	session[:user_id] = @user.id.to_s
            redirect_to root_url, notice: "Thank you for signing up!"
        else
            render "new"
        end
    end

    private
    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/garages_helper.rb
module GaragesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/garages/edit.html.erb
<div class = "container">

<h1> EDIT CAR</h1>



<%= form_for @garage do |f| %>

	<label>Date: </label><%= f.text_field :date, class: "form-control" %>
	<label>Year: </label><%= f.text_field :year, class: "form-control" %>
	<label>Model: </label><%= f.text_field :model, class: "form-control" %>
	<label>Price: </label><%= f.text_field :price, class: "form-control" %>
	<label>Mileage: </label><%= f.text_field :mileage, class: "form-control" %>
	<label>Phone: </label><%= f.text_field :phone, class: "form-control" %>
	<label>Email: </label><%= f.text_field :email, class: "form-control" %>
	<label>comments: </label><%= f.text_field :comments, class: "form-control" %>
	


<%= f.submit "EDIT CAR", class: "btn btn-warning" %>

<% end %>

<%= link_to "Back to the list", garages_path %>
</div>

app/views/garages/index.html.erb
<h1>Cars in Garage</h1>

<ul>
	<% @garages.each do |g| %>
	<li>
		<strong> <%= g.model %> </strong> -- <%= link_to "more details!", garage_path(g) %>
		
	</li>
 	
 	<% end %>
</ul>

app/views/garages/new.html.erb
<div class= "container">


<%= form_for @garage do |f| %>

<h1> ADD A NEW CAR</h1>

	<label>Date: </label><%= f.text_field :date, class: "form-control" %>
	<label>Year: </label><%= f.text_field :year, class: "form-control" %>
	<label>Model: </label><%= f.text_field :model, class: "form-control" %>
	<label>Price: </label><%= f.text_field :price, class: "form-control" %>
	<label>Mileage: </label><%= f.text_field :mileage, class: "form-control" %>
	<label>Phone: </label><%= f.text_field :phone, class: "form-control" %>
	<label>Email: </label><%= f.text_field :email, class: "form-control" %>
	<label>comments: </label><%= f.text_field :comments, class: "form-control" %>



<%= f.submit "Add Car" , class: "btn btn-success"%>

<% end %>

<%= link_to "Back to the list", garages_path %>
</div>

app/views/garages/show.html.erb
<h1> <%= @garage.model %> </h1>

<p> <%= @garage.year %> <%= @garage.make %>, <%= @garage.model %> with <%= @garage.mileage %> <%= @garage.model %>  for <%= @garage.price %>. call <%= @garage.phone %> to contact owner or email  </p>


<%= link_to "Edit this car", edit_garage_path %>

<%= link_to "Delete this car!", :garage, method: :delete, data: { confirm: 'Are you sure you want to delete it?' } %>

<%= link_to "back to list", garages_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Carshop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">

</head>
<body>

   	 <div id="container">
		<div id="user_header">
		    <% if current_user %>
		      Logged in as <%= current_user.email %>.
		      <%= link_to "Log Out", logout_path %>
		    <% else %>
		      <%= link_to "Sign Up", signup_path %> or
		      <%= link_to "Log In", login_path %>
		    <% end %>
		</div>
        <% flash.each do |name,msg| %>
            <%= content_tag :div, msg, id: "flash_#{name}" %>
        <% end %>

<%= yield %>
	</div>

</body>
</html>

app/views/users/index.html.erb
<div class= "container">

<p>I'm a place holder page. I'm located in <%= users_path %> /index.html.erb </p>

</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>